version: '3.8'
services:
  app:
    image: mintam141/miminiverse-app:latest
    build:
      context: .
      args:
        BUILD_VERSION: ${BUILD_VERSION:-latest}
    ports:
      - "3000:3000"
    restart: always
    environment:
      - BUILD_VERSION=c0e3ee487a73ddc2e10ea3ac127f538e5c169f0f
    deploy:
      labels:
        - "com.centurylinklabs.watchtower.enable=true"